backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "date", name: "date", widget: "datetime", default: "DD:MM:YYYY", date_format: "DD.MM.YYYY" }
      - { label: "Day-3-Letters", name: "day", widget: "string" }
      - { label: "Month-Day", name: "monthdate", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "City/Town", name: "city", widget: "string" }
      - { label: "Venue", name: "venue", widget: "string" }
      - { label: "Button", name: "buttontext", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }

